"""

Revision ID: bb451744e183
Revises: d01e0645d284
Create Date: 2024-10-05 13:43:07.324993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb451744e183'
down_revision: Union[str, None] = 'd01e0645d284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Enum('NO', 'JUNIOR', 'MIDDLE', 'SENIOR', name='experience'), nullable=True),
    sa.Column('busyness', sa.ARRAY(sa.Enum('FULL', 'PARTIAL', 'PROJECT', 'VOLUNTEERING', 'INTERNSHIP', 'GPH', name='busyness')), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_index(op.f('ix_vacancies_name'), 'vacancies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_name'), table_name='vacancies')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
